spring.application.name=inventory-service
server.port=0
eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_service_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Explicitly set the Dialect so Hibernate doesn't have to guess
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# 1. Tells Eureka to use the IP address for communication
# 1. Force the use of IP instead of hostname
eureka.instance.prefer-ip-address=true

# 2. Specifically tell Eureka to use the local loopback address
eureka.instance.ip-address=127.0.0.1

# 3. Rename the host to localhost to prevent DNS lookups
eureka.instance.hostname=localhost

# 4. Explicitly set the ID so it doesn't use the Desktop name
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]