spring.application.name=product-service
server.port=8081
eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka/
spring.data.mongodb.uri=mongodb://localhost:27017/product_db
# Disable docker compose to prevent it from forcing a local connection
spring.docker.compose.enabled=false
# 1. Tells Eureka to use the IP address for communication
eureka.instance.prefer-ip-address=true

# 2. Specifically tells Eureka WHICH IP to use (127.0.0.1 is safe for local dev)
eureka.instance.ip-address=127.0.0.1

# 3. Forces the hostname to localhost so Netty doesn't try DNS lookups

# 4. Explicitly set the ID so it doesn't use the Desktop name
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]