server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.enabled=false
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-hostname=false
spring.cloud.gateway.discovery.locator.enabled=false

# Routes
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:8181/realms/spring-boot-microservices-realm}

# Zipkin
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.zipkin.tracing.export.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,gateway
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ACT.apigateway=DEBUG